[mypy]
strict = true
warn_return_any = true
warn_unused_configs = true

[mypy-sense_hat.*]
ignore_missing_imports = true

[mypy-gpiozero.*]
ignore_missing_imports = true

[mypy-readchar.*]
ignore_missing_imports = true

[mypy-lgpio]
ignore_missing_imports = true

[mypy-hailo]
ignore_missing_imports = true
